### ISSUE TITLE
fetcher should support generic git

### ISSUE THREAD

**Issue by ChrisMacNaughton** [juju/charm-tools#124]
Limiting layers / interfaces to being hosted on Github and Launchpad is frustrating, I'd love to have support for generic git endpoints.

**Comment by verterok** [comment]
Looks like this is the culprit: https://github.com/juju/charm-tools/blob/master/charmtools/build/fetchers.py#L73

**Comment by marcoceppi** [comment]
This was fixed by #128

**Comment by tvansteenburgh** [comment]
Actually this is not really fixed. The only git fetchers we have at the moment are specific to Github and Launchpad. See https://github.com/juju/charm-tools/blob/master/charmtools/fetchers.py#L163, and also line 178.

It's simple to add new fetchers though. Since fetchers are based on regex matching, a generic git fetcher might just try to match on 'git'.

**Comment by ChrisMacNaughton** [comment]
or even git://.*.git to be more specific and match less things
