### ISSUE TITLE
The `charm build` fails with AttributeError: 'NoneType' object has no attribute 'combine'

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#273]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.2.0
charm-tools 2.1.5
```

I am using: Xenial

## Issue/Feature

I snap installed charm and am trying to build the etcd charm from its layer. https://github.com/juju-solutions/layer-etcd and I get an error when building.

### I expect/expected the following

I expect charm build to not error, or tell me how to fix the problem if it is in my code.

### What I got
```
$ charm build -r --no-local-layers
build: Composing into /home/mbruzek/workspace/charms
build: Destination charm directory: /home/mbruzek/workspace/charms/builds/etcd
build: Processing layer: layer:basic
build: Processing layer: layer:tls
build: Processing layer: layer:leadership
build: Processing layer: etcd
Traceback (most recent call last):
  File "/snap/charm/7/bin/charm-build", line 11, in <module>
    load_entry_point('charm-tools==2.1.5', 'console_scripts', 'charm-build')()
  File "/snap/charm/7/lib/python2.7/site-packages/charmtools/build/builder.py", line 676, in main
    build()
  File "/snap/charm/7/lib/python2.7/site-packages/charmtools/build/builder.py", line 519, in __call__
    self.generate()
  File "/snap/charm/7/lib/python2.7/site-packages/charmtools/build/builder.py", line 470, in generate
    self.formulate_plan(layers)
  File "/snap/charm/7/lib/python2.7/site-packages/charmtools/build/builder.py", line 411, in formulate_plan
    self.plan = self.plan_layers(layers, output_files)
  File "/snap/charm/7/lib/python2.7/site-packages/charmtools/build/builder.py", line 327, in plan_layers
    output_files=output_files))
  File "/snap/charm/7/lib/python2.7/site-packages/charmtools/build/builder.py", line 323, in <genexpr>
    list(e for e in utils.walk(layer.directory,
  File "/snap/charm/7/lib/python2.7/site-packages/charmtools/utils.py", line 345, in walk
    yield (entry, fn(entry, **kwargs))
  File "/snap/charm/7/lib/python2.7/site-packages/charmtools/build/builder.py", line 299, in build_tactics
    tactic = current.combine(existing)
AttributeError: 'NoneType' object has no attribute 'combine'
```

**Comment by wwwtyro** [comment]
:+1: also seeing this

**Comment by wwwtyro** [comment]
Looks like this might have been addressed in this commit: https://github.com/juju/charm-tools/commit/cd23ad6f3a7ad93d9404a6c9a60487960937151d

Not sure why I don't have this code, though - this is from August and we just got a new release. *shrug*

**Comment by axinojolais** [comment]
Hi,

This is still happening on a fresh layer-etc clone with the latest charm/charm-tools from ppa:juju/stable : 
```
axino@ubuntu ~/repos/layer-etcd % charm version
charm 2.2.0-0ubuntu1~ubuntu16.10.1~ppa2
charm-tools 2.1.9
axino@ubuntu ~/repos/layer-etcd % charm build -l DEBUG
build: Composing into /home/axino/repos/repository_juju
build: Destination charm directory: /home/axino/repos/repository_juju/builds/etcd
build: {
  "INTERFACE_PATH": null,
  "JUJU_REPOSITORY": "/home/axino/repos/repository_juju",
  "LAYER_PATH": null,
  "_charm": ".",
  "_charm_metadata": {
    "description": "This charm supports deploying Etcd from the upstream binaries with resources.\nIt will also TLS wrap your service, and distribute client keys to any service\nconnecting. Etcd is a highly available key/value store.\n",
    "maintainers": [
      "Charles Butler <charles.butler@canonical.com>"
    ],
    "name": "etcd",
    "peers": {
      "cluster": {
        "interface": "etcd"
      }
    },
    "provides": {
      "db": {
        "interface": "etcd"
      },
      "proxy": {
        "interface": "etcd-proxy"
      }
    },
    "resources": {
      "snapshot": {
        "description": "Tarball snapshot of an etcd clusters data.",
        "filename": "snapshot.tar.gz",
        "type": "file"
      }
    },
    "series": [
      "xenial"
    ],
    "storage": {
      "data": {
        "description": "Data volume to store the Etcd wal file and data.",
        "minimum-size": "1G",
        "multiple": {
          "range": "0-1"
        },
        "type": "block"
      }
    },
    "subordinate": false,
    "summary": "Deploy a TLS terminated ETCD Cluster",
    "tags": [
      "database",
      "keystore",
      "layer"
    ]
  },
  "_name": "etcd",
  "_top_layer": null,
  "config": "BuildConfig({'_tactics': [], 'configured': False})",
  "deps": "/home/axino/repos/repository_juju/deps",
  "description": false,
  "force": false,
  "hide_metrics": false,
  "interface_service": "http://interfaces.juju.solutions",
  "log_level": "DEBUG",
  "no_local_layers": false,
  "output_dir": "/home/axino/repos/repository_juju",
  "repo": "/home/axino/repos/repository_juju/builds",
  "report": false,
  "series": null,
  "target_dir": "/home/axino/repos/repository_juju/builds/etcd"
}
charmtools.fetchers: git clone https://github.com/juju-solutions/layer-basic.git /home/axino/repos/repository_juju/deps/layer/tmpe0dUDx: Cloning into '/home/axino/repos/repository_juju/deps/layer/tmpe0dUDx'...

charmtools.fetchers: git clone https://github.com/juju-solutions/layer-tls /home/axino/repos/repository_juju/deps/layer/tmpL2bTBw: Cloning into '/home/axino/repos/repository_juju/deps/layer/tmpL2bTBw'...

charmtools.fetchers: git clone https://github.com/juju-solutions/interface-tls /home/axino/repos/repository_juju/deps/interface/tmpyUMgXV: Cloning into '/home/axino/repos/repository_juju/deps/interface/tmpyUMgXV'...

charmtools.fetchers: git clone https://git.launchpad.net/layer-leadership /home/axino/repos/repository_juju/deps/layer/tmpmcF6gM: Cloning into '/home/axino/repos/repository_juju/deps/layer/tmpmcF6gM'...

charmtools.fetchers: git clone https://github.com/juju-solutions/interface-etcd /home/axino/repos/repository_juju/deps/interface/tmpMpkqkE: Cloning into '/home/axino/repos/repository_juju/deps/interface/tmpMpkqkE'...

charmtools.fetchers: git clone https://github.com/juju-solutions/interface-etcd-proxy /home/axino/repos/repository_juju/deps/interface/tmp7VRwEc: Cloning into '/home/axino/repos/repository_juju/deps/interface/tmp7VRwEc'...

build: Processing layer: layer:basic
build: Processing layer: layer:tls
build: Processing layer: layer:leadership
build: Processing layer: etcd
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 11, in <module>
    load_entry_point('charm-tools==2.1.9', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 676, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 519, in __call__
    self.generate()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 470, in generate
    self.formulate_plan(layers)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 411, in formulate_plan
    self.plan = self.plan_layers(layers, output_files)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 327, in plan_layers
    output_files=output_files))
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 323, in <genexpr>
    list(e for e in utils.walk(layer.directory,
  File "/usr/lib/python2.7/dist-packages/charmtools/utils.py", line 345, in walk
    yield (entry, fn(entry, **kwargs))
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 299, in build_tactics
    tactic = current.combine(existing)
AttributeError: 'NoneType' object has no attribute 'combine'

axino@ubuntu ~/repos/layer-etcd % git log -1
commit 2b2911f3579f74bfe40efc40b1c530d1fa438c5e
Merge: ac17e11 a8612b4
Author: Charles Butler <chuck@dasroot.net>
Date:   Thu Nov 17 10:49:22 2016 -0600

    Merge pull request #64 from mbruzek/new-flake8-rules

    Fixing the source with the new flake8 rules.
```
